app/account/urls.py
from django.urls import path

from account.views import (
    UserSignUpView,
    UserActivateView,
    ProfileView
)

app_name = 'account'


urlpatterns = [
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

app/currency/api/v1/urls.py
from rest_framework.routers import DefaultRouter

from currency.api.v1.views import RateViewSet, SourceViewSet, ContactUsViewSet

app_name = 'api-currency'

router = DefaultRouter()
router.register(r'rates', RateViewSet, basename='rates')
router.register(r'contact-us', ContactUsViewSet, basename='contact-us')
router.register(r'source', SourceViewSet, basename='source')

urlpatterns = [
    # path('rates/', RateApiView.as_view(), name='rates-list'),
    # path('rates/<int:pk>/', RateDetailApiView.as_view(), name='rates-detail')
]

urlpatterns += router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RateListView,
    RateCreateView,
    RateDetailView,
    RateUpdateView,
    RateDeleteView,
    ContactUsListView,
    ContactUsCreateView,
    ContactUsDetailView,
    ContactUsUpdateView,
    ContactUsDeleteView,
    SourceListView,
    SourceCreateView,
    SourceDetailView,
    SourceUpdateView,
    SourceDeleteView,
)


app_name = 'currency'


urlpatterns = [
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),

    path('contact-us/list/', ContactUsListView.as_view(), name='contact-us-list'),
    path('contact-us/create/', ContactUsCreateView.as_view(), name='contact-us-create'),
    path('contact-us/details/<int:pk>/', ContactUsDetailView.as_view(), name='contact-us-details'),
    path('contact-us/update/<int:pk>/', ContactUsUpdateView.as_view(), name='contact-us-update'),
    path('contact-us/delete/<int:pk>/', ContactUsDeleteView.as_view(), name='contact-us-delete'),

    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from currency.views import IndexView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

v1_url_patterns = [
    path('v1/api/currency/', include('currency.api.v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('', IndexView.as_view(), name='index'),

    path('currency/', include('currency.urls')),
    path('api/', include('account.api.urls')),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += v1_url_patterns

app/currency/models.py
from django.db import models
from django.utils import timezone
from django.templatetags.static import static
from currency.choices import RateCurrencyChoices


class Rate(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    currency = models.PositiveSmallIntegerField(
        choices=RateCurrencyChoices.choices,
        default=RateCurrencyChoices.USD
    )
    buy = models.DecimalField(max_digits=6, decimal_places=2)
    sale = models.DecimalField(max_digits=6, decimal_places=2)
    # source = models.CharField(max_length=25)
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f'Currency: {self.get_currency_display()}, Buy: {self.buy}'


class ContactUs(models.Model):
    created = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=128, default='')
    email_from = models.EmailField(max_length=40)
    subject = models.CharField(max_length=256)
    message = models.TextField()

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f'Email from: {self.email_from}, Subject: {self.subject}'


def logo_path(instance, filename):
    return f"logos/{instance.name}/{filename}"


class Source(models.Model):
    logo = models.FileField(
        default=None,
        null=True,
        blank=True,
        upload_to=logo_path
    )
    source_url = models.URLField(max_length=255)
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=64, unique=True)
    number = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    @property
    def logo_url(self):
        if self.logo:
            return self.logo.url

        return static('logo-unknown.jpg')


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=128)
    request_method = models.CharField(max_length=32)
    time = models.FloatField()

app/currency/forms.py
from django import forms

from currency.models import Rate, Source, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sale',
            'source',
            'currency'
        )


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'name',
            'email_from',
            'subject',
            'message'
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'logo',
            'source_url',
            'name',
            'number'
        )

app/currency/api/v1/views.py
from currency.paginators import RatesPagination, SourcePagination, ContactUsPagination
from currency.models import Rate, Source, ContactUs
from currency.api.v1.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from currency.filters import RateFilter, SourceFilter, ContactUsFilter
from currency.throttlers import AnonCurrencyThrottle
from currency.choices import RateCurrencyChoices
from currency import constants

from django.core.cache import cache
from django_filters import rest_framework as filters
from rest_framework import filters as rest_framework_filters

from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.permissions import AllowAny
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework_xml.renderers import XMLRenderer
from rest_framework_yaml.renderers import YAMLRenderer


# class RateApiView(generics.ListCreateAPIView):
#     queryset = Rate.objects.all().select_related('source')
#     serializer_class = RateSerializer # json dumps, json loads
#
#
# class RateDetailApiView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Rate.objects.all()
#     serializer_class = RateSerializer


class RateViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all()
    serializer_class = RateSerializer
    # renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = RatesPagination
    permission_classes = (AllowAny,)
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
    )
    filterset_class = RateFilter
    ordering_fields = ('id', 'created', 'buy', 'sale')
    throttle_classes = (AnonCurrencyThrottle,)

    @action(detail=False, methods=('GET',))
    def latest(self, request, *args, **kwargs):
        latest_rates = []

        cached_rates = cache.get(constants.LATEST_RATE_CACHE_KEY)
        if cached_rates:
            return Response(cached_rates)

        for source_obj in Source.objects.all():
            for currency in RateCurrencyChoices:
                latest = Rate.objects.filter(
                    source=source_obj,
                    currency=currency)\
                    .order_by('-created')\
                    .first()

                if latest:
                    latest_rates.append(RateSerializer(instance=latest).data)

        cache.set(constants.LATEST_RATE_CACHE_KEY, latest_rates, 60 * 60 * 24 * 7)

        return Response(latest_rates)


class SourceViewSet(viewsets.ModelViewSet):
    queryset = Source.objects.all()
    serializer_class = SourceSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = SourcePagination
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
        rest_framework_filters.SearchFilter,
    )
    filterset_class = SourceFilter
    ordering_fields = ('id', 'source_url', 'name', 'number')
    throttle_classes = (AnonCurrencyThrottle,)
    search_fields = ['name']


class ContactUsViewSet(viewsets.ModelViewSet):
    queryset = ContactUs.objects.all()
    serializer_class = ContactUsSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = ContactUsPagination
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
        rest_framework_filters.SearchFilter,
    )
    filterset_class = ContactUsFilter
    ordering_fields = ('id', 'name', 'email_from', 'subject', 'message')
    throttle_classes = (AnonCurrencyThrottle,)
    search_fields = ['name', 'subject']

app/currency/views.py
from currency.models import Rate, ContactUs, Source
from currency.forms import RateForm, SourceForm, ContactUsForm
from currency.filters import RateFilter, SourceFilter, ContactUsFilter

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, TemplateView
from django_filters.views import FilterView


class RateListView(FilterView):
    template_name = 'rates_list.html'
    queryset = Rate.objects.all().select_related('source')
    paginate_by = 10
    filterset_class = RateFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_pagination'] = '&'.join(
            f'{key}={value}' for key, value in self.request.GET.items() if key != 'page'
        )
        return context


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rates_details.html'


class RateCreateView(CreateView):
    form_class = RateForm
    template_name = 'rates_create.html'
    success_url = reverse_lazy('currency:rate-list')


class RateUpdateView(UserPassesTestMixin, UpdateView):
    form_class = RateForm
    template_name = 'rates_update.html'
    success_url = reverse_lazy('currency:rate-list')
    queryset = Rate.objects.all()

    def test_func(self):
        return self.request.user.is_superuser


class RateDeleteView(UserPassesTestMixin, DeleteView):
    queryset = Rate.objects.all()
    template_name = 'rates_delete.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class ContactUsListView(FilterView):
    template_name = 'contact_us_list.html'
    queryset = ContactUs.objects.all()
    paginate_by = 10
    filterset_class = ContactUsFilter


class ContactUsDetailView(DetailView):
    queryset = ContactUs.objects.all()
    template_name = 'contact_us_details.html'


class ContactUsCreateView(CreateView):
    form_class = ContactUsForm
    template_name = 'contact_us_create.html'
    success_url = reverse_lazy('currency:contact-us-list')

    def _send_mail(self):
        subject = 'User ContactUs'
        message = f'''
            Request from: {self.object.name}.
            Reply to email: {self.object.email_from}.
            Subject: {self.object.subject}.
            Body: {self.object.message}.
        '''
        from currency.tasks import send_mail
        # send_mail.delay(subject, message)
        # send_mail.apply_async(args=[subject, message])
        send_mail.apply_async(
            kwargs={'subject': subject, 'message': message},
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_mail()
        return redirect


class ContactUsUpdateView(UpdateView):
    form_class = ContactUsForm
    template_name = 'contact_us_update.html'
    success_url = reverse_lazy('currency:contact-us-list')
    queryset = ContactUs.objects.all()


class ContactUsDeleteView(DeleteView):
    queryset = ContactUs.objects.all()
    template_name = 'contact_us_delete.html'
    success_url = reverse_lazy('currency:contact-us-list')


class SourceListView(FilterView):
    template_name = 'source_list.html'
    queryset = Source.objects.all()
    paginate_by = 10
    filterset_class = SourceFilter


class SourceDetailView(DetailView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceCreateView(CreateView):
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:source-list')


class SourceUpdateView(UpdateView):
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:source-list')
    queryset = Source.objects.all()


class SourceDeleteView(DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source-list')


class IndexView(TemplateView):
    template_name = 'index.html'

app/currency/templates/contact_us.html
{% extends 'base.html' %}

{% block title %}
    Contact Us
{% endblock title %}

{% block caption %}
    Contact Us
{% endblock caption %}

{% block content %}

<thead>
  <tr bgcolor="yellow">
    <th>Id</th>
    <th>Email from</th>
    <th>Subject</th>
    <th>Message</th>
    <th>Update</th>
  </tr>
</thead>

<tbody>
{% for contact in contact_us %}
  <tr>
    <td>{{ contact.id }}</td>
    <td>{{ contact.email_from }}</td>
    <td>{{ contact.subject }}</td>
    <td>{{ contact.message }}</td>
    <td><a href="/contact-us/update/{{ contact.id }}/">Update</a></td>
  </tr>
{% endfor %}
</tbody>

{% endblock content %}

app/currency/templates/contact_us_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create Contact Us
{% endblock title %}

{% block content %}
    <h6>Create Contact Us Form</h6>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/contact_us_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Contact Us
{% endblock title %}

{% block content %}
    Do you really want to delete contact us with id {{ contactus.id }}?<br>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-info">Yes</button>
    </form>

{% endblock content %}

app/currency/templates/contact_us_details.html
{% extends 'base.html' %}

{% block title %}
    Contact Us
{% endblock title %}

{% block caption %}
    Contact Us
{% endblock caption %}

{% block content %}
  <a class="btn btn-outline-info" href="{% url 'currency:contact-us-create' %}">Create</a><br>

  <div class="row col-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email from</th>
                <th scope="col">Subject</th>
                <th scope="col">Message</th>
                <th scope="col">Created</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">#</th>
                    <td>{{ contactus.id }}</td>
                    <td>{{ contactus.name }}</td>
                    <td>{{ contactus.email_from }}</td>
                    <td>{{ contactus.subject }}</td>
                    <td>{{ contactus.message }}</td>
                    <td>{{ contactus.created }}</td>
                </tr>
            </tbody>
        </table>
  </div>

{% endblock content %}

app/currency/templates/contact_us_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Contact Us
{% endblock title %}

{% block caption %}
    Contact Us
{% endblock caption %}

{% block content %}
  <a class="btn btn-outline-info" href="{% url 'currency:contact-us-create' %}">Create</a><br>
  <form method="get">
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ filter.form.name__contains|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ filter.form.subject__contains|as_crispy_field }}
      </div>
    </div>
    <input type="submit" class="btn btn-outline-info" value="Submit" />
  </form>
  <br>
  <div class="row col-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email from</th>
                <th scope="col">Subject</th>
                <th scope="col">Message</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for contactus in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ contactus.id }}</td>
                    <td>{{ contactus.name }}</td>
                    <td>{{ contactus.email_from }}</td>
                    <td>{{ contactus.subject }}</td>
                    <td>{{ contactus.message }}</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown"
                                    aria-expanded="false">
                                Actions
                            </button>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" href="{% url 'currency:contact-us-details' contactus.id %}">Details</a>
                              <a class="dropdown-item" href="{% url 'currency:contact-us-update' contactus.id %}">Update</a>
                              <a class="dropdown-item" href="{% url 'currency:contact-us-delete' contactus.id %}">Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
  </div>

{% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock title %}

{% block content %}

<h6>Hello from INDEX</h6>

{% endblock content %}

app/currency/templates/rates_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create Rates
{% endblock title %}

{% block content %}
    <h6>Create Rate Form</h6>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/rates_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Rates
{% endblock title %}

{% block content %}
    Do you really want to delete rate with id {{ rate.id }}?<br>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-info">Yes</button>
    </form>

{% endblock content %}

app/currency/templates/rates_details.html
{% extends 'base.html' %}

{% block title %}
    Rates
{% endblock title %}

{% block caption %}
    Rates
{% endblock caption %}

{% block content %}
  <a class="btn btn-outline-info" href="{% url 'currency:rate-create' %}">Create</a><br>

  <div class="row col-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Buy</th>
                <th scope="col">Sale</th>
                <th scope="col">Currency</th>
                <th scope="col">Source</th>
                <th scope="col">Created</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">#</th>
                    <td>{{ rate.id }}</td>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.sale }}</td>
                    <td>{{ rate.get_currency_display }}</td>
                    <td>{{ rate.source.name }}</td>
                    <td>{{ rate.created }}</td>
                </tr>
            </tbody>
        </table>
  </div>

{% endblock content %}

app/currency/templates/rates_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Rates
{% endblock title %}

{% block caption %}
    Rates
{% endblock caption %}

{% block content %}
  <a class="btn btn-outline-info" href="{% url 'currency:rate-create' %}">Create</a><br>
  <br>
  <form method="get">
    <a class="btn btn-outline-info" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Filters Set
    </a>
    <div class="collapse" id="collapseExample">
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ filter.form.buy__gte|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ filter.form.buy__lte|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ filter.form.sale__gte|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ filter.form.sale__lte|as_crispy_field }}
        </div>
      </div>
      <input type="submit" class="btn btn-outline-info" value="Submit" />
    </div>
  </form>
  <br>
  <div class="row col-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Buy</th>
                <th scope="col">Sale</th>
                <th scope="col">Currency</th>
                <th scope="col">Source</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for rate in page_obj %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ rate.id }}</td>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.sale }}</td>
                    <td>{{ rate.get_currency_display }}</td>
                    <td>{{ rate.source.name }}</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown"
                                    aria-expanded="false">
                                Actions
                            </button>
                            <div class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                  <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                  {% if request.user.is_superuser %}
                                    <a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Update</a>
                                    <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                                  {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Create Source
{% endblock title %}

{% block content %}
    <h6>Create Source Form</h6>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/source_details.html
{% extends 'base.html' %}

{% block title %}
    Source
{% endblock title %}

{% block caption %}
    Source
{% endblock caption %}

{% block content %}
  <a class="btn btn-outline-info" href="{% url 'currency:source-create' %}">Create</a><br>

  <div class="row col-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Logo</th>
                <th scope="col">Source URL</th>
                <th scope="col">Name</th>
                <th scope="col">Number</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">#</th>
                    <td>{{ source.id }}</td>
                    <td><img src="{{ source.logo_url }}" class="img-fluid img-thumbnail" alt="BankLogo" width="50"></td>
                    <td>{{ source.source_url }}</td>
                    <td>{{ source.name }}</td>
                    <td>{{ source.number }}</td>
                </tr>
            </tbody>
        </table>
  </div>

{% endblock content %}

app/currency/templates/source_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Source
{% endblock title %}

{% block caption %}
    Source
{% endblock caption %}

{% block content %}
  <a class="btn btn-outline-info" href="{% url 'currency:source-create' %}">Create</a><br>
  <form method="get">
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ filter.form.name__contains|as_crispy_field }}
      </div>
    </div>
    <input type="submit" class="btn btn-outline-info" value="Submit" />
  </form>
  <br>
  <div class="row col-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Logo</th>
                <th scope="col">Source URL</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for source in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ source.id }}</td>
                    <td><img src="{{ source.logo_url }}" class="img-fluid img-thumbnail" alt="BankLogo" width="50"></td>
                    <td>{{ source.source_url }}</td>
                    <td>{{ source.name }}</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown"
                                    aria-expanded="false">
                                Actions
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'currency:source-details' source.id %}">Details</a>
                                <a class="dropdown-item" href="{% url 'currency:source-update' source.id %}">Update</a>
                                <a class="dropdown-item" href="{% url 'currency:source-delete' source.id %}">Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
  </div>

{% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/source_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Update Source
{% endblock title %}

{% block content %}
    <h6>Update Source Form</h6>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>

{% endblock content %}